"""init

Revision ID: 51f2f3830120
Revises: e084bf35b799
Create Date: 2023-08-16 14:01:40.818626

"""
import pgvector.sqlalchemy
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '51f2f3830120'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('collection_id', sa.Integer(), nullable=True),
                    sa.Column('source_id', sa.Integer(), nullable=True),
                    sa.Column('source_index', sa.Integer(), nullable=True),
                    sa.Column('title', sa.String(length=500), nullable=True),
                    sa.Column('content', sa.Text(), nullable=True),
                    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document')
    # ### end Alembic commands ###
