"""embedding_half

Revision ID: 887edb10e659
Revises: 51f2f3830120
Create Date: 2024-02-23 16:48:03.221446

"""
import pgvector.sqlalchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '887edb10e659'
down_revision = '51f2f3830120'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('embedding_half', pgvector.sqlalchemy.Vector(dim=768), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'embedding_half')
    # ### end Alembic commands ###
